[package]
name = "sha256_cracker"
version = "0.1.0"
authors = ["Felix Figueroa"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10.7"
hex = "0.4.3"
sha2 = "0.10.8"
